---
title: "eBooks"
output: html_document
---

---

<link href="../docs/site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="../docs/site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

```{r pkgs, include = F}
knitr::opts_chunk$set(dev = 'png', 
                      echo = FALSE,
                      message = FALSE)
packages <- c("readr", "glue", "tidyverse", "psych", "zoo")
xfun::pkg_attach(packages, message = F)
```

```{r paths}
in_paths <- list()
in_paths['books'] <- "../data/books.csv"
in_paths['collaborator_urls'] <- "../data/collaborator-urls.csv"
in_paths['tag_colors'] <- "../data/tag-colors.csv"
```

```{r}
df <- read_csv(in_paths[['books']]) %>%
  mutate(date = glue("{year}-{str_pad(month, 2, 'left', 0)}"),
         date_r = as.Date(glue("{year}-{month}-01"))) %>%
  arrange(desc(date_r))
df_collab <- read_csv(in_paths[['collaborator_urls']])
df_tags <- read_csv(in_paths[['tag_colors']])
```

```{r, results = 'asis'}
html_row <- function(df, i) {
  code <- glue("<div class='divTableRow'>")
  code <- glue("{code}<div style='width: 100px;' class='divTableCell'>{df$date[i]}</div>")
  code <- glue("{code}<div class='divTableCell'>")
  
  # title
  code <- glue("{code}<div class='divBlogTitle'>")
  if (df$link_new_window[i] == TRUE) {
    code <- glue("{code}<a href='{df$link[i]}' target='_blank'>{df$title[i]}</a>")
  } else {
    code <- glue("{code}<a href='{df$link[i]}'>{df$title[i]}</a>")
  }
  
  if (!is.na(df$github_link[i])) {
    code <- glue("{code} <a href='{df$github_link[i]}' target='_blank'><span class='fa fa-github'></span></a>")
  }
  
  code <- glue("{code}</div>")
  
  code <- glue("{code}<br>{df$description[i]}")
  
  # tags
  tags <- str_split(df$tags[i], ",") %>% unlist() %>% sort()
  tags_code <- ""
  for (j in 1:length(tags)) {
    tag_color <- df_tags$color[which(df_tags$tag == tags[j])]
    tags_code <- glue("{tags_code} <span class='badge badge-pill badge-{tag_color}'>{tags[j]}</span>")
  }
  
  code <- glue("{code}<br>*Tags*: {tags_code}")
  
  code <- glue("{code}</div></div>")
  
  return(code)
}

code_all <- "<div class='divTable'><div class='divTableBody'><div class='divTableRow'><div class='divTableCell'>**Date**</div><div class='divTableCell'>**Book**</div></div>"
for (i in 1:nrow(df)) {
  code_all <- glue("{code_all}<br>{html_row(df, i)}")
}

code_all <- glue("{code_all}</div></div>")

# link collaborators to their respective website
for (i in 1:nrow(df_collab)) {
  code_all <- str_replace_all(code_all, df_collab$collaborator[i], glue("<a href='{df_collab$link[i]}' target='_blank'>{df_collab$collaborator[i]}</a>"))
}

cat(code_all)
```