project:
  type: website

website:
  title: "Ekarin Eric Pongpipat, Ph.D."
  navbar:
    search: true
    right:
      - icon: journals
        text: Blog
        href: blog.qmd
      - icon: book
        text: Books
        href: books.qmd
      - icon: "bi bi-file-earmark-person"
        text: "CV"
        href: cv.qmd
      - icon: github
        text: GitHub
        href: https://github.com/epongpipat
      - text: Connect
        menu:
        - icon: linkedin
          text: LinkedIn
          href: https://www.linkedin.com/in/epongpipat/
        - text: ResearchGate
          href: https://www.researchgate.net/profile/Ekarin-Pongpipat
        - icon: twitter-x
          text: X
          href: https://x.com/epongpipat
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

