---
title: "Blog"
subtitle: "Mostly a reference"
output: html_document
---

<BR><BR>

<div class="divTable">
<div class="divTableBody">

<div class="divTableRow"><div class="divTableCell">
**Date**
</div><div class="divTableCell">
**Post**
</div></div>

<!-- <div class="divTableRow"><div class="divTableCell"> -->
<!-- 2018-03-13 -->
<!-- </div><div class="divTableCell"> -->
<!-- <div class="divBlogTitle"> -->
<!-- [Introductory Univariate Statistics in Psychology Performed as General Linear Models (GLM) in R](blog_Introductory_Univariate_Statistics_in_Psychology_Performed_as_General_Linear_Models_in_R.html) -->
<!-- </div> -->
<!-- A terse comparison of typical introductory univariate statistics in psychology performed as GLMs in R. -->
<!-- <BR>*Tags:* <span class="badge badge-pill badge-light">Statistics</span> -->
<!-- <span class="badge badge-pill badge-primary">R</span> -->
<!-- </div></div> -->

<div class="divTableRow"><div class="divTableCell">
2018-06-17
</div><div class="divTableCell">
<div class="divBlogTitle">
<a href="https://epongpipat.shinyapps.io/lmvoice/" target="_blank">Simple Linear Regression via Voice Command: A Shiny App</a>
</div>
Change variables of a simple linear regression via voice commands. *(Note: Link may or not work depending on if my free hours have been used up for the month, but feel free to download the code and run locally from my <a href="https://github.com/epongpipat/epongpipat.github.io/tree/master/shinyApps/lmVoice" target="_blank">github</a>.)*
<BR>*Tags:* <span class="badge badge-pill badge-light">Statistics</span>
<span class="badge badge-pill badge-primary">R</span>
<span class="badge badge-pill badge-primary">Shiny Apps</span>
</div></div>

<BR>

<div class="divTableRow"><div class="divTableCell">
2018-06-07
</div><div class="divTableCell">
<div class="divBlogTitle">
<a href="https://mattkmiecik.com/post-Bootstrapping-and-Permutation-Testing-Shiny-App.html" target="_blank">Bootstrapping and Permutation Testing: A Shiny App</a>
</div>
A collaboration post with [Matt Kmiecik](https://mattkmiecik.com) about the differences between bootstrapping and permutation testing with input variables that change on the fly.
<BR>*Tags:* <span class="badge badge-pill badge-light">Statistics</span>
<span class="badge badge-pill badge-primary">R</span>
<span class="badge badge-pill badge-primary">Shiny Apps</span>
</div></div>

<BR>

<div class="divTableRow"><div class="divTableCell">
2018-03-20
</div><div class="divTableCell">
<div class="divBlogTitle">
[Calculate Motion Regressors](blog_Calculate_Motion_Regressors.html)
</div>
A quick guide to calculating motion regressors (with visuals).
<BR>*Tags:* <span class="badge badge-pill badge-dark">fMRI</span>
<span class="badge badge-pill badge-primary">R</span>
</div></div>

<BR>

<div class="divTableRow"><div class="divTableCell" style="width: 100px;">
2018-02-11
</div><div class="divTableCell">
<div class="divBlogTitle">
<a href="https://mattkmiecik.com/post-Multilevel-Modeling-in-R-with-NHL-Power-Play-Data.html" target="_blank">Multilevel Modeling in R with NHL Power Play Data</a>
</div>
A collaboration post with [Matt Kmiecik](https://mattkmiecik.com) about multilevel modeling in R using professional hockey data from the NHL.
<BR>*Tags:* <span class="badge badge-pill badge-light">Statistics</span>
<span class="badge badge-pill badge-primary">R</span>
</div></div>

</div>
</div>