on:
  push:
    paths:
      - '*.Rmd'
      - '*.csv'
  pull_request:
    paths:
      - '*.Rmd'
      - '*.csv'

name: render rmds

jobs:
  render:
    name: render rmds
    build:
      runs-on: macOS-latest
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v2
        - uses: r-lib/actions/setup-r@master
        - uses: r-lib/actions/setup-pandoc@master
        - name: Install dependencies
        run: |
          install.packages("xfun")
          pkgs <- c('rmarkdown')
          xfun::pkg_attach2(pkgs)
        shell: Rscript {0}

        - name: Render Rmarkdown files
          run: |
            RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
            Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f, output_dir = "docs/")' ${RMD_PATH[*]} 

        - name: Commit results
          run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add docs/
            git commit -m 'commit docss'
            git push origin
